

import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from "next/script";
import NextTopLoader from "nextjs-toploader";



import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import Head from "next/head";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
  <Script
    id="ga-gtag-init"
    strategy="beforeInteractive"
    dangerouslySetInnerHTML={{
      __html: `
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-XC6TT41V9E');
      `,
    }}
  />

  {/* Google Tag Manager (in <head>) */}
  <Script
    id="gtm-script"
    strategy="beforeInteractive"
    dangerouslySetInnerHTML={{
      __html: `
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-KH8ZPGBR');
      `,
    }}
  />

 <Script
        id="ld-json-org"
        type="application/ld+json"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": "Neon Mortgage",
            "url": "https://neonmortgage.com",
            "sameAs": [
              "https://www.instagram.com/neonmortgage"
            ]
          }),
        }}
      />
  {/* Hotjar */}
  <Script
    id="hotjar-init"
    strategy="beforeInteractive"
    dangerouslySetInnerHTML={{
      __html: `
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:5231751,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
      `,
    }}
  />
  </head>


      <Script
    strategy="afterInteractive"
    src="https://www.googletagmanager.com/gtag/js?id=G-XC6TT41V9E"
  />


      <body>
         <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-KH8ZPGBR"
              height="0"
              width="0"
              style={{ display: 'none', visibility: 'hidden' }}
            ></iframe>
          </noscript>
      
        <NextTopLoader style={{zIndex: '9999999'}} color="#000" height={3} />

        <LayoutWrapper>
        {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
